01.Full.smd
NAME_LOCALE{"EN-US", "Full"}
NAME_LOCALE{"ZH-CN", "完整"}

IETF_LOCALE{ComboButtonFormat, "EN-US", "Hold %s to exit"}
IETF_LOCALE{ComboButtonFormat, "ZH-CN", "按住 %s 退出"}
;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_ShowRealFrequencies_Description = Show real frequencies for CPU, GPU and RAM. Shows up only when hoc-clk or sys-clk is detected running.
;;User_ShowRealFrequencies_Name = Show real frequencies
;;User_ShowTargetFrequencies_Description = Show target frequencies for CPU, GPU and RAM.
;;User_ShowTargetFrequencies_Name = Show target frequencies
;;User_ShowFrequenceDeltas_Description = Show difference between real frequency and target frequency. Shows up only when hoc-clk or sys-clk is detected running.
;;User_ShowFrequenceDeltas_Name = Show frequency deltas
;;User_ShowFPS_Description = Shows FPS value when game runs. Shows up only when SaltyNX is detected running.
;;User_ShowFPS_Name = Show FPS
;;User_ShowResolution_Description = Shows two most likely candidates for rendering resolution of currently running game. Shows up only when SaltyNX is detected running.
;;User_ShowResolution_Name = Show resolutions
;;User_ShowReadSpeed_Description = Shows game's read speed in MiB/s. Shows up only when SaltyNX is detected running.
;;User_ShowReadSpeed_Name = Show game's read speed
;;User_OldFpsAverage_Description = Don't clamp FPS if they are in close range of PFPS value.
;;User_OldFpsAverage_Name = Use old FPS averaging.

IETF_LOCALE{TargetFreqTextFormat,      "EN-US", "Target Frequency: %u.%u MHz"}
IETF_LOCALE{RealFreqTextFormat,        "EN-US", "Real Frequency: %u.%u MHz"}
IETF_LOCALE{CPULoadTextFormat,         "EN-US", "Core #0: %.2lf%%\nCore #1: %.2lf%%\nCore #2: %.2lf%%\nCore #3: %.2lf%%"}
IETF_LOCALE{GPULoadTextFormat,         "EN-US", "Load: %u.%u%%"}
IETF_LOCALE{RAMLoadTextFormat,         "EN-US", "Load: %u.%u%% (CPU %u.%u | GPU %u.%u)"}
IETF_LOCALE{RAMUsageBaseTextFormat,    "EN-US", "Total: \nApplication: \nApplet: \nSystem: \nSystem Unsafe: "}
IETF_LOCALE{BatteryChargingTextFormat, "EN-US", "Battery Power Flow: %+.2fW[%s]"}
IETF_LOCALE{FanRotationTextFormat,     "EN-US", "Fan Rotation Level: %2.1f%%"}
IETF_LOCALE{FpsNDText,                 "EN-US", "PFPS: n/d; FPS: n/d"} (n/d - no data)
IETF_LOCALE{ReadSpeedTextFormat,       "EN-US", "Read speed: %.2f MiB/s"}
IETF_LOCALE{ReadSpeedUnkTextFormat,    "EN-US", "Read speed: n/d"} (n/d - no data)
IETF_LOCALE{CpuUsageText,              "EN-US", "CPU Usage:"}
IETF_LOCALE{GpuUsageText,              "EN-US", "GPU Usage:"}
IETF_LOCALE{RamUsageText,              "EN-US", "RAM Usage:"}
IETF_LOCALE{BoardUsageText,            "EN-US", "Board:"}
IETF_LOCALE{TemperatureText,           "EN-US", "Temperatures:"}
IETF_LOCALE{ThermalSensorsText,        "EN-US", "SOC \nPCB \nSkin "}
IETF_LOCALE{GameText,                  "EN-US", "Game:"}
IETF_LOCALE{Resolutions1Text,          "EN-US", "Resolutions: %dx%d"}
IETF_LOCALE{Resolutions2Text,          "EN-US", "Resolutions: %dx%d || %dx%d"}
IETF_LOCALE{TargetFreqTextFormat,      "ZH-CN", "目标频率：%u.%u MHz"}
IETF_LOCALE{RealFreqTextFormat,        "ZH-CN", "实际频率：%u.%u MHz"}
IETF_LOCALE{CPULoadTextFormat,         "ZH-CN", "核心 #0：%.2lf%%\n核心 #1：%.2lf%%\n核心 #2：%.2lf%%\n核心 #3：%.2lf%%"}
IETF_LOCALE{GPULoadTextFormat,         "ZH-CN", "负载：%u.%u%%"}
IETF_LOCALE{RAMLoadTextFormat,         "ZH-CN", "负载：%u.%u%%（CPU %u.%u | GPU %u.%u）"}
IETF_LOCALE{RAMUsageBaseTextFormat,    "ZH-CN", "总计：\n应用：\n小程序：\n系统：\n系统未保护："}
IETF_LOCALE{BatteryChargingTextFormat, "ZH-CN", "电池功率流：%+.2fW[%s]"}
IETF_LOCALE{FanRotationTextFormat,     "ZH-CN", "风扇转速：%2.1f%%"}
IETF_LOCALE{FpsNDText,                 "ZH-CN", "PFPS：n/d；FPS：n/d"}
IETF_LOCALE{ReadSpeedTextFormat,       "ZH-CN", "读取速度：%.2f MiB/s"}
IETF_LOCALE{ReadSpeedUnkTextFormat,    "ZH-CN", "读取速度：n/d"}
IETF_LOCALE{CpuUsageText,              "ZH-CN", "CPU 使用率："}
IETF_LOCALE{GpuUsageText,              "ZH-CN", "GPU 使用率："}
IETF_LOCALE{RamUsageText,              "ZH-CN", "RAM 使用率："}
IETF_LOCALE{BoardUsageText,            "ZH-CN", "主板："}
IETF_LOCALE{TemperatureText,           "ZH-CN", "温度："}
IETF_LOCALE{ThermalSensorsText,        "ZH-CN", "SOC \nPCB \n外壳 "}
IETF_LOCALE{GameText,                  "ZH-CN", "游戏："}
IETF_LOCALE{Resolutions1Text,          "ZH-CN", "分辨率：%dx%d"}
IETF_LOCALE{Resolutions2Text,          "ZH-CN", "分辨率：%dx%d || %dx%d"}

02.Mini.smd
NAME_LOCALE{"EN-US", "Mini"}
NAME_LOCALE{"ZH-CN", "迷你"}
;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_ShowRealFrequencies_Description = Show real frequencies instead of target frequencies for CPU, GPU and RAM. Shows up only when hoc-clk or sys-clk is detected running.
;;User_ShowRealFrequencies_Name = Show real frequencies
;;User_CategoryColor_Description = Color of categories (left column of text).
;;User_CategoryColor_Name = Data type color
;;User_TextColor_Name = Data color
;;User_BoxColor_Name = Background color
;;User_HandheldFontSize_Description = Size of text in handheld mode.
;;User_HandheldFontSize_Name = Font size
;;User_DockedFontSize_Description = Size of text in docked mode.
;;User_DockedFontSize_Name = Docked font size
;;User_ShowCPU_Name = Show CPU data
;;User_ShowGPU_Name = Show GPU data
;;User_ShowRAM_Name = Show RAM data
;;User_ShowRAMLoad_Description = Show RAM load instead of used memory space. Shows only when hoc-clk or sys-clk is running.
;;User_ShowRAMLoad_Name = Show RAM load
;;User_ShowTEMP_Description = Shows as TEMP
;;User_ShowTEMP_Name = Show temperatures
;;User_ShowDRAW_Description = Shows Battery data related to power flow and time left to discharge battery completely.
;;User_ShowDRAW_Name = Show battery draw
;;User_ShowFAN_Name = Show fan rotation level
;;User_ShowFAN_Description = Shows up as FAN (this is not showing for English language for obvious reason)
;;User_ShowFPS_Description = Shows only when game is running and SaltyNX is running.
;;User_ShowFPS_Name = Show FPS
;;User_OldFpsAverage_Description = Don't clamp FPS if they are in close range of PFPS value.
;;User_OldFpsAverage_Name = Use old FPS averaging.
;;User_ShowRES_Description = Show two most likely candidated for currently running game's rendering resolution. Shows only when game is running and SaltyNX is running.
;;User_ShowRES_Name = Show resolutions
;;User_ShowREAD_Description = Shows only when game is running and SaltyNX is running.
;;User_ShowREAD_Name = Show game's read speed
;;User_Ordering_Description = In which order should data be rendered from top to bottom.
;;User_Ordering_Name = Data order

03.Micro.smd
NAME_LOCALE{"EN-US", "Micro"}
NAME_LOCALE{"ZH-CN", "微型"}
;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_CategoryColor_Name = Data type color
;;User_TextColor_Name = Data color
;;User_BoxColor_Name = Background color
;;User_HandheldFontSize_Description = Size of text in handheld mode.
;;User_HandheldFontSize_Name = Font size
;;User_DockedFontSize_Description = Size of text in docked mode.
;;User_DockedFontSize_Name = Docked font size
;;User_TextPosition_Description = 0 - to left. 1 - centered. 2 - to right.
;;User_TextPosition_Name = Text alignment
;;User_ShowCPU_Name = Show CPU data
;;User_ShowGPU_Name = Show GPU data
;;User_ShowRAM_Name = Show RAM data
;;User_ShowRAMLoad_Description = Show RAM load instead of used memory space. Shows only when hoc-clk or sys-clk is running.
;;User_ShowRAMLoad_Name = Show RAM load
;;User_ShowBRD_Description = Shows up as BRD. PCB/SoC/Skin temperatures + Battery data related to power flow and time left to discharge battery completely.
;;User_ShowBRD_Name = Show battery draw and temperatures
;;User_ShowFAN_Description = Show fan rotation level in percentage.
;;User_ShowFAN_Name = Show fan rotation level
;;User_ShowFPS_Description = Shows up only when game is running and SaltyNX is running.
;;User_ShowFPS_Name = Show FPS
;;User_OldFpsAverage_Description = Don't clamp FPS if they are in close range of PFPS value.
;;User_OldFpsAverage_Name = Use old FPS averaging.
;;User_Ordering_Description = In which order should data be rendered from left to right.
;;User_Ordering_Name = Data order

IETF_LOCALE{NoDataText, "EN-US", "n/d"} (no data)
IETF_LOCALE{NoDataText, "ZH-CN", "n/d"}

FPS/01.FPSGraph.smd
NAME_LOCALE{"EN-US", "Graph"}
NAME_LOCALE{"ZH-CN", "图表"}
;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_FpsCounterColor_Description = It's behind graph when game runs.
;;User_FpsCounterColor_Name = FPS Counter color
;;User_BorderColor_Name = Graph border color
;;User_DashedLineColor_Description = It's in the middle of graph.
;;User_DashedLineColor_Name = Dashed line color
;;User_MainLineColor_Name = Graph's main line color
;;User_RoundedLineColor_Description = Color of line if rounded FPS value is equal to half of refresh rate.
;;User_RoundedLineColor_Name = Half display refresh rate color
;;User_PerfectLineColor_Description = Color of line if rounded FPS value is equal to refresh rate.
;;User_PerfectLineColor_Name = Full display refresh rate color
;;User_BoxColor_Name = Background color
;;User_MinValueColor_Description = Is printed on the bottom left.
;;User_MinValueColor_Name = "0" color
;;User_MaxValueColor_Description = It is printed on the top left.
;;User_MaxValueColor_Name = Display refresh rate value color
;;User_OldFpsAverage_Description = Don't clamp FPS if they are in close range of PFPS value.
;;User_OldFpsAverage_Name = Use old FPS averaging.
;;User_GraphWidth_Name = Graph's width
;;User_GraphHeight_Name = Graph's height
;;User_AdjustToRefreshRate_Name = Adjust graph's height to display refresh rate

FPS/02.FPSCounter.smd
NAME_LOCALE{"EN-US", "Counter"}
NAME_LOCALE{"ZH-CN", "计数器"}

;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_TextColor_Name = FPS value color
;;User_HandheldFontSize_Description = Size of text in handheld mode.
;;User_HandheldFontSize_Name = Font size
;;User_DockedFontSize_Description = Size of text in docked mode.
;;User_DockedFontSize_Name = Docked font size
;;User_OldFpsAverage_Description = Don't clamp FPS if they are in close range of PFPS value.
;;User_OldFpsAverage_Name = Use old FPS averaging.

Other/01.BatteryCharger.smd
NAME_LOCALE{"ZH-CN", "电池/充电器"}
IETF_LOCALE{Text01Format, "EN-US", "Battery Actual Capacity: %.0f mAh\n"}
IETF_LOCALE{Text02Format, "EN-US", "Battery Designed Capacity: %.0f mAh\n"}
IETF_LOCALE{Text03Format, "EN-US", "Battery Temperature: %.1f°C\n"}
IETF_LOCALE{Text04Format, "EN-US", "Battery Raw Charge: %.1f%%\n"}
IETF_LOCALE{Text05Format, "EN-US", "Battery Age: %.1f%%\n"}
IETF_LOCALE{Text06Format, "EN-US", "Battery Voltage (%ds AVG): %.0f mV\n"}
IETF_LOCALE{Text07Format, "EN-US", "Battery Current Flow (%ss AVG): %+.0f mA\n"}
IETF_LOCALE{Text08Format, "EN-US", "Battery Power Flow%s: %+.3f W\n"}
IETF_LOCALE{Text09Format, "EN-US", "Battery Remaining Time: %s\n"}
IETF_LOCALE{Text10Format, "EN-US", "Charger Type: %u\n"}
IETF_LOCALE{Text11Format, "EN-US", "Charger Max Voltage: %u mV\n"}
IETF_LOCALE{Text12Format, "EN-US", "Charger Max Current: %u mA\n"}
IETF_LOCALE{Avg5s,        "EN-US", " (5s AVG)"}
IETF_LOCALE{Title,        "EN-US", "Battery/Charger Stats:"}
IETF_LOCALE{Text01Format, "ZH-CN", "电池实际容量：%.0f mAh\n"}
IETF_LOCALE{Text02Format, "ZH-CN", "电池设计容量：%.0f mAh\n"}
IETF_LOCALE{Text03Format, "ZH-CN", "电池温度：%.1f°C\n"}
IETF_LOCALE{Text04Format, "ZH-CN", "电池当前电量：%.1f%%\n"}
IETF_LOCALE{Text05Format, "ZH-CN", "电池使用年龄：%.1f%%\n"}
IETF_LOCALE{Text06Format, "ZH-CN", "电池电压（%ds 平均）：%.0f mV\n"}
IETF_LOCALE{Text07Format, "ZH-CN", "电池电流（%ss 平均）：%+.0f mA\n"}
IETF_LOCALE{Text08Format, "ZH-CN", "电池功率流%s：%+.3f W\n"}
IETF_LOCALE{Text09Format, "ZH-CN", "电池剩余时间：%s\n"}
IETF_LOCALE{Text10Format, "ZH-CN", "充电器类型：%u\n"}
IETF_LOCALE{Text11Format, "ZH-CN", "充电器最大电压：%u mV\n"}
IETF_LOCALE{Text12Format, "ZH-CN", "充电器最大电流：%u mA\n"}
IETF_LOCALE{Avg5s,        "ZH-CN", "（5s 平均）"}
IETF_LOCALE{Title,        "ZH-CN", "电池/充电器统计："}

Other/02.Miscellaneous.smd
NAME_LOCALE{"EN-US", "Miscellaneous"}
NAME_LOCALE{"ZH-CN", "杂项"}

IETF_LOCALE{MultimediaText,   "EN-US", "Multimedia clock rates:"}
IETF_LOCALE{NetworkText,      "EN-US", "Network:"}
IETF_LOCALE{WiFiText,         "EN-US", "Type: Wi-Fi"}
IETF_LOCALE{ShowPasswordText, "EN-US", "Press Y to show password"}
IETF_LOCALE{EthernetText,     "EN-US", "Type: Ethernet"}
IETF_LOCALE{NotConnectedText, "EN-US", "Type: Not connected"}
IETF_LOCALE{MultimediaText,   "ZH-CN", "多媒体时钟频率："}
IETF_LOCALE{NetworkText,      "ZH-CN", "网络："}
IETF_LOCALE{WiFiText,         "ZH-CN", "类型：Wi-Fi"}
IETF_LOCALE{ShowPasswordText, "ZH-CN", "按 Y 显示密码"}
IETF_LOCALE{EthernetText,     "ZH-CN", "类型：以太网"}
IETF_LOCALE{NotConnectedText, "ZH-CN", "类型：未连接"}

Other/03.GameResolutions.smd
NAME_LOCALE{"EN-US", "Game resolutions"}
NAME_LOCALE{"ZH-CN", "游戏分辨率"}
;;User_RefreshRate_Description = Max refresh rate of rendered overlay. It won't be faster than your current display refresh rate because of vsync.
;;User_RefreshRate_Name = Refresh rate
;;User_TextColor_Name = Data color
;;User_CategoryColor_Name = Data type color
;;User_BoxColor_Name = Background color
;;User_WarningColor_Description = Color of text when no game is running or no valid data is detected.

IETF_LOCALE{WarningText, "EN-US", "Game is not running or it's incompatible."}
IETF_LOCALE{WarningText, "ZH-CN", "游戏未运行或不兼容。"}

Also:
- translate folder name Other in Other/_folder.ini
